name: joke_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.5

  # Firebase core for initialization
  firebase_core: ^2.8.0

  # Firestore (to store favorites)
  cloud_firestore: ^4.7.0

  # Firebase messaging (push notifications)
  firebase_messaging: ^14.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
